//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id_customer { get; set; }
        public int id_product { get; set; }
        public int id { get; set; }
        public System.DateTime order_date { get; set; }
        public string order_qty { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
